# configuration file
networks:
    ethmain:
        type: ethereum
        url: wss://rinkeby.infura.io/ws/v3/918963fae0a24ff4beafa5f080d659df 

accounts:
    # simple account monitor, from or to
    0x137d9174d3bd00f2153dcc0fe7af712d3876a71e:
        network : ethmain

alerts:
    # scan smartcontract action
    createSiringAuction:
        network : ethmain
        rule: (to == '0x291e668c675e8ae47eb2f0523f4736c5e11b6f39')
        message: Somebody made me a transfer 


    # check events in all transactions if there’s my account in the 0x6e81… topic of the 0x7d13… contract
    deepanalisys:
        network : ethmain
        rule: (log_0x7d1335Af903ff256823c9AA2d4a5aaA41E054335_0x6e812926864597b1b871e35c4b24bd297ec1e96c871c41b9d7d3deb47bbe751c =~ '137d9174d3bd00f2153dcc0fe7af712d3876a71e')
        message: Somebody made me a transfer 

notifications:
    telegramusername: adriamb
